export { default as isTextEmpty } from './isTextEmpty'
export { default as removeWhiteSpace } from './removeWhiteSpace'
export { default as getPriceDiscount } from './getPriceDiscount'
export { default as getUniqueItemsFromList } from './getUniqueItemsFromList'
export { default as getSameItemCountFromList } from './getSameItemCountFromList'
export { default as getSortedListByAZ } from './getSortedListByAZ'
export { default as getSortedByDate } from './getSortedByDate'
export { default as getSortedPriceByDiscount } from './getSortedPriceByDiscount'
