export { default as isTextEmpty } from './isTextEmpty'
export { default as removeWhiteSpace } from './removeWhiteSpace'
export { default as getPriceDiscount } from './getPriceDiscount'
export { default as getUniqueItemsFromList } from './getUniqueItemsFromList'
export { default as getSameItemCountFromList } from './getSameItemCountFromList'
